apiVersion: apps/v1
kind: Deployment
metadata:
  name: githubby-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: githubby-app
  template:
    metadata:
      labels:
        app: githubby-app
    spec:
      containers:
      - name: githubby-container
        image: your-docker-image-goes-here # Opsera/Argo will fill this in later!
        ports:
        - containerPort: 8080
