name: Build and push image

# Triggers: push to main, Opersa repository_dispatch, and manual run in UI
on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [opersa-run]
  workflow_dispatch:
    inputs:
      pipeline:
        description: 'Pipeline name (optional)'
        required: false
        default: 'build'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.app
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/githubby:latest
            ghcr.io/${{ github.repository_owner }}/githubby:${{ github.sha }}
